version: '3.4'

services:
  nginx:
    image: nginx
    volumes:
      - .:/app
      - ./docker/nginx/templates/app.conf.template:/etc/nginx/conf.d/app.conf
#      - ./docker/nginx/templates/:/etc/nginx/templates
    environment:
      VIRTUAL_HOST: 'xdebug.localhost'
    networks:
      - default
      - frontend

  php:
    build: ./docker/php/
    working_dir: /app
    volumes:
    - .:/app
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini

networks:
  frontend:
    external:
      name: nginxproxy_general-proxy